/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.rafaeljpc.oauth2.study

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class AuthApp

fun main(args: Array<String>) {
    runApplication<AuthApp>(*args)
}