/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.rafaeljpc.oauth2.study

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = AuthApp()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
