/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.rafaeljpc.oauth2.study

import io.github.rafaeljpc.oauth2.study.config.AuthAppConfig
import org.springframework.boot.context.properties.ConfigurationProperties
import org.springframework.boot.test.autoconfigure.web.reactive.AutoConfigureWebTestClient
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.context.annotation.Import
import kotlin.test.Test


@SpringBootTest(
    webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
    classes = [AuthAppTestConfig::class, AuthApp::class]
)
class AuthAppTest {

    @Test
    fun contextLoad() {
    }
}

@AutoConfigureWebTestClient
@Import(AuthAppConfig::class)
class AuthAppTestConfig

@ConfigurationProperties(prefix = "auth.app.test.client")
data class ClientConfig(
    val grantType: String = "",
    val clientId: String = "",
    val clientSecret: String = "",
    val audience: String = "",
    val tokenUrl: String = "",
)