auth0:
  audience: ${AUDIENCE:https://some-api/api}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:https://your-domain.auth0.com/}
          audiences:
            - ${auth0.audience}
  jpa:
    show-sql: true
